// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzjKRBTQtIynw-IV1JyqgqJPy2JLhKwo',
    appId: '1:298051505132:web:7dc0c482108fd2f9168ec9',
    messagingSenderId: '298051505132',
    projectId: 'expense-pro-d90e1',
    authDomain: 'expense-pro-d90e1.firebaseapp.com',
    storageBucket: 'expense-pro-d90e1.firebasestorage.app',
    measurementId: 'G-R1033TV52D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx95hB__l4GOeb6h187146FIjGHq5-eEQ',
    appId: '1:298051505132:android:2c8802700dce357c168ec9',
    messagingSenderId: '298051505132',
    projectId: 'expense-pro-d90e1',
    storageBucket: 'expense-pro-d90e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9emoyiC53leAmxpRUywpT92jbE7KuqmQ',
    appId: '1:298051505132:ios:b4786bfe192ca2e5168ec9',
    messagingSenderId: '298051505132',
    projectId: 'expense-pro-d90e1',
    storageBucket: 'expense-pro-d90e1.firebasestorage.app',
    iosBundleId: 'com.example.expensePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9emoyiC53leAmxpRUywpT92jbE7KuqmQ',
    appId: '1:298051505132:ios:b4786bfe192ca2e5168ec9',
    messagingSenderId: '298051505132',
    projectId: 'expense-pro-d90e1',
    storageBucket: 'expense-pro-d90e1.firebasestorage.app',
    iosBundleId: 'com.example.expensePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzjKRBTQtIynw-IV1JyqgqJPy2JLhKwo',
    appId: '1:298051505132:web:78bc689af8c92832168ec9',
    messagingSenderId: '298051505132',
    projectId: 'expense-pro-d90e1',
    authDomain: 'expense-pro-d90e1.firebaseapp.com',
    storageBucket: 'expense-pro-d90e1.firebasestorage.app',
    measurementId: 'G-HE5LQP5H1F',
  );
}
